{
 "title": "shoehub dashboard",
 "description": "Mon premier dashboard grafana",
 "tags": [
  "test shoehub",
  "test",
  "online course"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"}, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "paymentMethod",
    "query": {
     "query": "label_values(shoehub_payments{}, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Payments in US (Gauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shoehub_payments{CountryCode=\"US\"}",
     "legendFormat": "{{PaymentMethod}}"
    }
   ]
  },
  {
   "title": "Payment amounts by $paymentMethod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "shoehub_payments{ PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rate(shoehub_sales[1m])", "legendFormat": "{{ShoeType}}" },
    { "expr": "sum(rate(shoehub_sales[1m]))", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Tech charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(microsoft_aspnetcore_hosting_http_server_request_duration_sum[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buisiness charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Card payments in Country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"US\"}) by (PaymentMethod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"US\"})",
     "legendFormat": "Total US payments"
    }
   ]
  },
  {
   "title": "Card Payments by Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(shoehub_payments{PaymentMethod=\"Card\"}) by (CountryCode)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sales today vs Sales Last Week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval] offset 2m)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pourcentage of Payment Methods in the $country (practice 47)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "repeat": "country",
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Paypal"
    }
   ]
  }
 ]
}